<Project>

    <PropertyGroup>
        <Product>Oro</Product>
        <Copyright>Copyright © 2025 Dust in the Wind</Copyright>

        <Version>1.0.0</Version>
        <Authors>Alexandru Iuga</Authors>
        <Company>Dust in the Wind</Company>

        <LangVersion>latest</LangVersion>
		
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/lastunicorn/oro-avalonia</RepositoryUrl>
		<PackageProjectUrl>https://github.com/lastunicorn/oro-avalonia</PackageProjectUrl>
    </PropertyGroup>

</Project>
